#!/usr/bin/env bash

script_dir="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"

# Add the current script dir to path if it's not there
if [[ ! "$PATH" =~ (^|:)"$script_dir"(:|$) ]]; then
    export PATH="${PATH}:${script_dir}"
fi

echo ""
cmsg -c "Install the redis server"
#----------------------------------------------
apt-get install -y redis-server
#----------------------------------------------
cmsg -c "done!..."
echo ""

echo ""
cmsg -c "Checking to see if redis is working. Should say: 'PONG'"
#----------------------------------------------
echo ""
echo ""
redis-cli ping
echo ""
echo ""
#----------------------------------------------
cmsg -c "done!..."
echo ""
