#!/usr/bin/env bash

if [ -L "$0" ]; then
    REPO_DIR="$(dirname "$(dirname "$(readlink "$0")")")"
else
    REPO_DIR="$(cd "$(dirname "$(dirname "$0")")" > /dev/null 2>&1 && pwd -P)"
fi

# The GitPython package will error unless this env variable is set
export GIT_PYTHON_REFRESH="0"
python3 "${REPO_DIR}/sutler" "$@"
