#!/usr/scripts/env bash

# Variables
CWD="$(pwd)"
script_dir="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
repos_dir="${HOME}/repos"
system="$1"

# Add the current script dir to path if it's not there
if [[ ! "$PATH" =~ (^|:)"$script_dir"(:|$) ]]; then
    export PATH="${PATH}:${script_dir}"
fi

# Check if the system argument was given
if [ -z "$system" ] || { [ "$system" != "desktop" ] && [ "$system" != "mac" ] && [ "$system" != "server" ]; }; then
    cmsg -an "Must specify a type of system. "
    cmsg -a  "Valid types: {desktop|mac|server}"
    exit 1
fi

# Create the repos directory if it doesn't exist
if [ ! -d "$repos_dir" ]; then
    mkdir -p "$repos_dir"
fi

# Clone or update the dotfiles repo
if [ -d "${repos_dir}/dotfiles" ]; then
    cd "${repos_dir}/dotfiles" && git pull
else
    cd "$repos_dir" && git clone "https://github.com/joeladam518/dotfiles.git"

    # Confirm cloning went ok
    if [ ! -d "${repos_dir}/dotfiles" ]; then
        cmsg -r "Failed to clone the dotfiles repo"
        exit 1
    fi
fi

# Call the install script
"$repos_dir"/dotfiles/install.sh "$system"

cd "$CWD" || exit
exit
